### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by artzet-s** [openalea/phenomenal#1]

**Comment by pradal** [comment]
I can do that.

**Comment by artzet-s** [comment]
Great, just make a pull request fort that, i want first tag a 2.7 version in phenomenal 1.6 and after put phenomenal in python 3.5

**Comment by pradal** [comment]
👍 My branch will be py3

**Comment by pradal** [comment]
I recommend to go directly on Python 3.7

**Comment by pradal** [comment]
Finally not. Not all the dependencies are available on Python 3.7

**Comment by pradal** [comment]
openalea.deploy is now on conda-forge

**Comment by pradal** [comment]
- Can you add me to readthedocs
- Move from nosetests to pytest
- Use modernize to go from Python 2 to Python 3

**Comment by artzet-s** [comment]
#11

**Comment by artzet-s** [comment]
closed #11
