### ISSUE TITLE
Uncalibrated Images

### ISSUE THREAD

**Issue by eyildiz-ugoe** [openalea/phenomenal#30]
I have a set of uncalibrated stereo images of a plant that I want to 3dreconstruct. I was wondering if the proposed pipeline works on uncalibrated images or could it automatically calculate the features and come up with a guess of the calibration matrix?

**Comment by christian34** [comment]
Unfortunately the answer is no: Phenomenal needs camera/image to be calibrated with checkerboard prior being able to reconstruct the plant.
