### ISSUE TITLE
vtk not functional after conda windows install

### ISSUE THREAD

**Issue by christian34** [openalea/phenomenal#5]
installing phenomenal on windows with (which is the recommended method on home page): 
`conda` install -c openalea -c conda-forge openalea.phenomenal

select vtk7.0.0-py27_vc9_1      conda-forge [vc9], which result in a non-functional vtk (import error)

Forcing to vtk=6.3.0 solve the problem for me

**Comment by artzet-s** [comment]
> Forcing to vtk=6.3.0 solve the problem for me

Ok I close the issue then.
